### ISSUE TITLE
Teleport not working

### ISSUE THREAD

**Issue by BrutalCSEjziponken** [ThaPwned/WCS#1]
Cant get Teleport as human to work. Not with new race nor the old one. Running CSGO.

         IMPORTANT: Please copy the full output.
         --------------------------------------------------------
         Checksum      : f0cf4eb8336078e645ac9bb0bb3fcf02
         Date          : 2019-01-20 16:15:59.049048
         OS            : Linux-4.12.12-gentoo-x86_64-Intel-R-_Xeon-R-_CPU_E5-1630_v3_@_3.70GHz-with-gentoo-2.4.1
         Game          : csgo
         SP version    : 677
         Github commit : 7ea507d83fccc3b1c7e1c475e36e3decbecff298
         Server plugins:
            00: Source.Python, (C) 2012-2018, Source.Python Team.
            01: Metamod:Source 1.11.0-dev+1116
         SP plugins:
            00: es_emulator, https://github.com/Ayuto/EventScripts-Emulator
            01: wcs, 2018.12.17-2, https://forums.sourcepython.com/viewtopic.php?f=7&t=1925

**Comment by ThaPwned** [comment]
Thanks for reporting! Could you try the new version and see if you still have this issue?
