### ISSUE TITLE
cant get player weapon

### ISSUE THREAD

**Issue by msmaiaa** [ThaPwned/WCS#15]
So, basically when a race tries to get the enemy weapon info, it returns an error in the console
code: es wcsx get weapon wcs_wpn server_var(wcs_player)
![Screenshot_30](https://user-images.githubusercontent.com/30882102/73073219-9fc8af00-3e95-11ea-8a4b-77c502d6a6be.png)
I was looking on the weapon lib and i saw that i need to pass an attribute like "weapon name" or "weapon maxammo" and i couldnt make it work, what can i do?
code: es wcsx get weapon,name wcs_wpn server_var(wcs_player)
![Screenshot_31](https://user-images.githubusercontent.com/30882102/73073531-4d3bc280-3e96-11ea-956c-a73a9d10cd23.png)

**Comment by ThaPwned** [comment]
Thanks for reporting! The first exception is fixed in the latest version of WCS. The other exception, however, you need to wait for Ayuto to accept a PR for the EventScripts Emulator for it to be fixed.

**Comment by msmaiaa** [comment]
thank you, do i just need to extract the stuff that changed in the server folders?

**Comment by msmaiaa** [comment]
thank you for fixing the error, i have another question, is levelbank compatible with this version of wcs? because i only found old stuff

**Comment by msmaiaa** [comment]
i saw that the data folder has a levelbank file, but i dont know how to use it, if you can guide me on how to use it i would appreciate that
