### ISSUE TITLE
levelbank 

### ISSUE THREAD

**Issue by msmaiaa** [ThaPwned/WCS#16]
i saw that the data folder has a levelbank file, but i dont know how to use it, if you can guide me on how to use it i would appreciate that

**Comment by msmaiaa** [comment]
also if levelbank doesnt work, can i use old versions like this (http://warcraft-source.com/board/index.php?topic=14864.0) ?

**Comment by ThaPwned** [comment]
> i saw that the data folder has a levelbank file, but i dont know how to use it, if you can guide me on how to use it i would appreciate that

There's no levelbank for this WCS. It might've been from one of your earlier installations.
> also if levelbank doesnt work, can i use old versions like this (http://warcraft-source.com/board/index.php?topic=14864.0) ?

Unfortunately, that levelbank is not compatible with this WCS. As of now, there's no plan to add one.
