### ISSUE TITLE
LevelBank

### ISSUE THREAD

**Issue by Asolez** [ThaPwned/WCS#17]
hi, I saw that you said there is no plan to add levelbank, but would you agree to do one? i can pay you

**Comment by ThaPwned** [comment]
> hi, I saw that you said there is no plan to add levelbank, but would you agree to do one?

I can make it if there's enough demand for one. It's not a high priority of mine right now.
> i can pay you

Thanks for the offer but I don't like taking donations for this project. If you feel like making a donation to someone, however, please send one to the Source-Python development team ([if they ever decide to get a donation button](https://forums.sourcepython.com/viewtopic.php?f=9&t=2036)) as this project would never have been where it is today without them.

**Comment by Asolez** [comment]
> > oi, vi que você disse que não há plano para adicionar levelbank, mas você concorda em fazer um?
> 
> Eu posso fazer isso se houver demanda suficiente para um. Não é uma alta prioridade minha agora.
> 
> > eu posso pagar você
> 
> Obrigado pela oferta, mas não gosto de receber doações para este projeto. Se você deseja fazer uma doação para alguém, no entanto, envie uma para a equipe de desenvolvimento do Source-Python ( [se eles decidirem obter um botão de doação](https://forums.sourcepython.com/viewtopic.php?f=9&t=2036) ), pois esse projeto nunca estaria onde está hoje sem eles.

Ok, I understand, ty for your attention
