### ISSUE TITLE
playerset model and command issues

### ISSUE THREAD

**Issue by msmaiaa** [ThaPwned/WCS#18]
First problem: when i try to use the playerset model like the screenshot below, it works when i enter the server, but if i change to another race that uses this command with another model, it doesn't change, its stays with the first model that i used, but if i change to another race without this command, it works perfectly fine (back to the original ct or t model)
![Screenshot_38](https://user-images.githubusercontent.com/30882102/74096884-7178df80-4ae3-11ea-9f85-e71573e52f6d.png)

Second problem: it seems like the wcs is having conflicts with another plugins. I have a !ws plugin etc but if i type the command in chat, the menu doesnt show (the game detects that is a command or something because it doesnt show in the chat), same thing with a store plugin, already tried both without wcs and it worked. I always get this error messages on the console and maybe its related to my problems. Thanks for the support. 
![Screenshot_37](https://user-images.githubusercontent.com/30882102/74096918-054aab80-4ae4-11ea-8888-281d432e1890.png)

**Comment by msmaiaa** [comment]
also when i use the playerset model the races go crazy and start doing weird bugs like giant error messages

**Comment by ThaPwned** [comment]
> First problem: when i try to use the playerset model like the screenshot below, it works when i enter the server, but if i change to another race that uses this command with another model, it doesn't change, its stays with the first model that i used, but if i change to another race without this command, it works perfectly fine (back to the original ct or t model)
> ![Screenshot_38](https://user-images.githubusercontent.com/30882102/74096884-7178df80-4ae3-11ea-9f85-e71573e52f6d.png)

Does this also happen when you manually try to set the player's model directly from the console? It might be a problem with the playerset model command on CSGO.
> Second problem: it seems like the wcs is having conflicts with another plugins. I have a !ws plugin etc but if i type the command in chat, the menu doesnt show (the game detects that is a command or something because it doesnt show in the chat), same thing with a store plugin, already tried both without wcs and it worked. I always get this error messages on the console and maybe its related to my problems. Thanks for the support.
> ![Screenshot_37](https://user-images.githubusercontent.com/30882102/74096918-054aab80-4ae4-11ea-8888-281d432e1890.png)

WCS doesn't register any command with a "!" as a prefix, so I'm not sure what's going on there. The fact that it just silently eat said command should point to an error of some kind occuring in the other plugin. What's weird is that it works fine without WCS...

> also when i use the playerset model the races go crazy and start doing weird bugs like giant error messages

That could happen if the model you're pointing to doesn't exist on the player's computer. Make sure it's the correct path and the model is downloadable.

**Comment by msmaiaa** [comment]
the command problem was actually caused by a plugin, that was my bad. About the model, they work with plugins that change models (store etc), the fastdl is setup correctly, i dont know how to explain but everything in wcs starts getting weird when i use a race with models, sometimes random races get the model too

**Comment by msmaiaa** [comment]
since im here i also would like to report more issues: wcs_dealdamage is actually doing half of the damage, and spawncmds doesnt seem to work pretty well, it works only when the player dies, for example: a knife only race that has restrict all on the spawncmd, if he changes to this race while dead, the restrict wont work, only if he dies while using that race.
