### ISSUE TITLE
how to add a new iteams

### ISSUE THREAD

**Issue by 7ancy** [ThaPwned/WCS#22]
I want to add products. I have tested several writing methods, but they are not effective. Can you give me a detailed demonstration, please

**Comment by 7ancy** [comment]
![image](https://user-images.githubusercontent.com/64363457/89046271-4d55d700-d37f-11ea-828d-da5211403dcc.png)

**Comment by ThaPwned** [comment]
Hey, it appears you forgot to add the "test" category to the "maxitems". It'd look as follows:
```json
    "maxitems": {
        "test": 3
    }
```
The 3 is how many items the players can purchase from that category.

**Comment by 7ancy** [comment]
thanks
