### ISSUE TITLE
i can't add admin

### ISSUE THREAD

**Issue by 7ancy** [ThaPwned/WCS#23]
{
    "players": {
        "STEAM_0:1:52288860": {
            "wcsadmin": 1,
            "wcsadmin_githubaccess": 1,
            "wcsadmin_managementaccess": 1,
            "wcsadmin_playersmanagement": 1,
            "wcsadmin_raceaccess": 1,
            "vip_raceaccess": 1
        }
    }	
	
}

This is my profile, but I still don't have permission after I enter the game

**Comment by ManifestManah** [comment]
Hi 7ancy!

If you could join the Warcraft-Source modification's official discord server, then I would very much like to assist and help you out with this WCS Admin problem that you are having :-)

On the discord you'll find many veterans and knowledgable people who can help out with this and other WCS related issues that you might encounter :-)

Here is the link: 
https://discord.gg/zYASbKz

**Comment by ThaPwned** [comment]
You can try to change `STEAM_0` to `STEAM_1`, and see if that fixes it. You can also try to use your steamid3 instead which'd be `[U:1:104577721]`.

**Comment by 7ancy** [comment]
> You can try to change `STEAM_0` to `STEAM_1`, and see if that fixes it. You can also try to use your steamid3 instead which'd be `[U:1:104577721]`.

steamid3 is work

**Comment by 7ancy** [comment]
> Hi 7ancy! (^.^)
> 
> If you could join the Warcraft-Source modification's official discord server, then I would very much like to assist and help you out with this WCS Admin problem that you are having.
> 
> On the discord you'll find many veterans and knowledgable people who can help out with this and other WCS related issues that you might encounter. :-)
> 
> Here is the link:
> https://discord.gg/zYASbKz

I joined discord, but I couldn't see the channel information
