### ISSUE TITLE
wcshelp[suggest]

### ISSUE THREAD

**Issue by 7ancy** [ThaPwned/WCS#25]
Can you make this menu optional, not just a command prompt
and
Some menus do not override the existing menu after inputting the command, which can only be seen after closing

**Comment by ThaPwned** [comment]
> Can you make this menu optional, not just a command prompt

What do you mean with making the menu optional?

If you, however, mean the help menu that shows when a player joins, that can be disabled by setting `wcs_welcome_gui_text` to `0` in the `cfg/source-python/wcs/config.cfg` file. The menu only shows up if the player's total level is below the value of `wcs_disable_text_on_level` which is `20` by default.

> Some menus do not override the existing menu after inputting the command, which can only be seen after closing

This is how the menus in Source.Python works: If a player has a menu shown, and you send a new menu, the new menu won't show until the player is done with the first menu.

**Comment by 7ancy** [comment]
Thank you for your explanation, I am using source python for the first time
