### ISSUE TITLE
New races doe not fire events

### ISSUE THREAD

**Issue by BrutalCSkakan** [ThaPwned/WCS#3]
https://cdn.discordapp.com/attachments/159002601646587905/537004806854672385/unknown.png

Some additional information, it does not seem that skill.execute works properly, it never fires the actual code for "player_ability".
Although the __init__ is firing from the human_alliance folder on load, but never seem to be firing after it's been read once. 

![image](https://user-images.githubusercontent.com/8394703/51522649-29304600-1e2a-11e9-95f2-4516d390c454.png)

I've copied the full plugin from the latest build, and afterwards I'm pasting the races into the correct folder. The races is loading as I can choose them in changerace, and simple things like invisibility seems to work. 
I cannot see that Im missing any files..

**Comment by ThaPwned** [comment]
Could you try with the newest version? I've changed the way the function execute, so that'd have fixed the issue you've been having.

**Comment by BrutalCSEjziponken** [comment]
**This is the log with YOUR new races and no eventscript running:
Still human can not teleport. I get NO chat message about failed teleport or cool downs or anything.**

>          IMPORTANT: Please copy the full output.
>          --------------------------------------------------------
>          Checksum      : 6fc2341cd7e2f2201c77f6ba54df2018
>          Date          : 2019-01-22 13:45:58.688564
>          OS            : Linux-4.12.12-gentoo-x86_64-Intel-R-_Xeon-R-_CPU_E5-1650_v4_@_3.60GHz-with-gentoo-2.4.1
>          Game          : csgo
>          SP version    : 677
>          Github commit : 7ea507d83fccc3b1c7e1c475e36e3decbecff298
>          Server plugins:
>             00: Source.Python, (C) 2012-2018, Source.Python Team.
>             01: Metamod:Source 1.11.0-dev+1116
>          SP plugins:
>             00: wcs, 2019.01.22-3, https://forums.sourcepython.com/viewtopic.php?f=7&t=1925
>          --------------------------------------------------------

```
2019-01-22 14:44:14 - sp	-	INFO	Checking for data updates...
2019-01-22 14:44:15 - sp	-	INFO	No new data is available.
2019-01-22 14:44:15 - sp	-	MESSAGE	[SP] Loading plugin 'wcs'...
2019-01-22 14:44:15 - sp	-	WARNING	
[SP] Encountered a Warning:
  File '../addons/source-python/plugins/wcs/core/constants/__init__.py', line 107: UserWarning
    IS_ESC_SUPPORT_ENABLED was set to True but EventScripts was not found

2019-01-22 14:44:15 - sp	-	WARNING	
[SP] Encountered a Warning:
  File '../addons/source-python/plugins/wcs/core/modules/races/manager.py', line 192: UserWarning
    Unable to find the default race "". Using "night_elves" as temporary default
        race.

2019-01-22 14:44:15 - sp	-	MESSAGE	[SP] Successfully loaded plugin 'wcs'.
2019-01-22 14:44:18 - sp	-	INFO	Core hook (run_command) has been initialized.
2019-01-22 14:44:34 - sp	-	EXCEPTION	
[SP] Caught an Exception:
Traceback (most recent call last):
  File "<string>", line 1, in <lambda>
  File "../addons/source-python/plugins/wcs/wcs.py", line 716, in on_player_delete
    wcsplayer.execute(event.name, event)
  File "../addons/source-python/plugins/wcs/core/players/entity.py", line 685, in execute
    assert self.ready

AssertionError
```

**Now if we try the old races/items. We run into problems. The default paths with 0.78 version are:**

/source-python/plugins/es_emulator/eventscripts/wcs/races
/source-python/plugins/es_emulator/eventscripts/wcs/tools

But the server will crash. Because with your version they need to be in:

/source-python/plugins/es_emulator/eventscripts/wcs/modules/races
/source-python/plugins/es_emulator/eventscripts/wcs/modules/items

**And the race.ini (also the 0.78 version has this renamed to default_races.ini) and tools.ini all point to tools, not items and they are missing the modules folder aswell. And the old race files are also sometimes pointing to the wrong folders.

Im not sure, but maybe this is enough to change:**

```
# EventScripts module path
MODULE_PATH_ES = PLUGIN_PATH / 'es_emulator' / 'eventscripts' / 'wcs' / 'modules'
# EventScripts race path
RACE_PATH_ES = MODULE_PATH_ES / 'races'
# EventScripts item path
ITEM_PATH_ES = MODULE_PATH_ES / 'items'

**to:**

# EventScripts module path
MODULE_PATH_ES = PLUGIN_PATH / 'es_emulator' / 'eventscripts' / 'wcs'
# EventScripts race path
RACE_PATH_ES = MODULE_PATH_ES / 'races'
# EventScripts item path
ITEM_PATH_ES = MODULE_PATH_ES / 'tools'

```

**Now when I run the server again and load everything I get this:**

```
Initializing EventScripts...
[EventScripts] Temporary: Setting the host's IP variable from the command-line.
[EventScripts] Loaded esc
[SP] Successfully loaded plugin 'es_emulator'.
[SP] Loading plugin 'wcs'...

[SP] Encountered a Warning:
  File '../addons/source-python/plugins/wcs/core/modules/races/manager.py', line 192: UserWarning
    Unable to find the default race "". Using "undead_scourge" as temporary default
        race.

[SP] Successfully loaded plugin 'wcs'.
[EventScripts] Loaded wcs/races
[EventScripts] Loaded wcs/races/warden
[EventScripts] Loaded wcs/races/archmage_proudmoore
[EventScripts] Loaded wcs/races/blood_mage
[EventScripts] Loaded wcs/races/human_alliance
[EventScripts] Loaded wcs/races/night_elves
[EventScripts] Loaded wcs/races/orcish_horde
[EventScripts] Loaded wcs/races/shadow_hunter
[EventScripts] Loaded wcs/races/undead_scourge
[EventScripts] Loaded wcs/races/crypt_lord
[EventScripts] Loaded wcs/races/flame_predator
[EventScripts] Loaded wcs/races/succubus_hunter
[EventScripts] Loaded wcs/tools
[EventScripts] Loaded wcs/tools/abilities
Can't load addon (wcs/tools/abilities/warden): cannot import name 'wcsgroup'
Can't load addon (wcs/tools/abilities/healingwarden): cannot import name 'wcsgroup'
Can't load addon (wcs/tools/abilities/trap): cannot import name 'wcsgroup'
Tried to look up command wcs_foreach as if it were a variable.

[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/plugins/es_emulator/eventscripts/esc/__init__.py", line 189, in command
    command.run(argv, args, exp)
  File "../addons/source-python/plugins/es_emulator/eventscripts/esc/cmds/__init__.py", line 140, in run
    self.method(**_args)
  File "../addons/source-python/plugins/es_emulator/eventscripts/esc/cmds/addons.py", line 20, in load
    es.load(addonname)
  File "../addons/source-python/plugins/es_emulator/eventscripts/esc/monkeypatch.py", line 28, in load
    load(addonname)
  File "../addons/source-python/plugins/es_emulator/helpers.py", line 206, in wrapper
    return func(c)
  File "../addons/source-python/plugins/es_emulator/eventscripts/es_C.py", line 2155, in load
    es.loadModuleAddon(argv[1])
  File "../addons/source-python/plugins/es_emulator/eventscripts/es.py", line 443, in loadModuleAddon
    addons.load(newaddon)
  File "../addons/source-python/plugins/es_emulator/eventscripts/es.py", line 242, in load
    addon.load()
  File "../addons/source-python/plugins/es_emulator/eventscripts/wcs/tools/foreach/foreach.py", line 7, in load
    registerServerCommand('wcs_foreach', register, 'Syntax: wcs_foreach <player/weapon/token> <var> <identifier> <"command">')
  File "../addons/source-python/plugins/es_emulator/eventscripts/_libs/python/cmdlib.py", line 141, in registerServerCommand
    cmd_manager.registerServerCommand(*a, **kw)
  File "../addons/source-python/plugins/es_emulator/eventscripts/_libs/python/cmdlib.py", line 37, in registerServerCommand
PreMinidumpCallback: updating dump comment
./srcds_run: line 318: 26682 Segmentation fault      $HL_CMD
Add "-debug" to the ./srcds_run command line to generate a debug.log to help with solving this problem
Tue Jan 22 15:28:43 CET 2019: Server restart in 10 seconds
crash_20190122152841_1.dmp[26692]: Uploading dump (out-of-process)
/tmp/dumps/crash_20190122152841_1.dmp
crash_20190122152841_1.dmp[26692]: Finished uploading minidump (out-of-process): success = yes
crash_20190122152841_1.dmp[26692]: response: Discarded=1
crash_20190122152841_1.dmp[26692]: file ''/tmp/dumps/crash_20190122152841_1.dmp'', upload yes: ''Discarded=1''
```

**So I edit the es_tools.txt And remove a few lines..** 

```
block load
{
	es_load wcs/tools/ultimates
	es_load wcs/tools/xcommands
	es_load wcs/tools/trap
}

block unload
{
	es_unload wcs/tools/ultimates
	es_unload wcs/tools/xcommands
	es_unload wcs/tools/trap
}
```
**Now the server starts, without a crash. Now when I teleport I actually get the message "You teleported" and also the message about cool downs.

And the log looks like this:**

```
[wcs/tools/ultimates/default/wcs_ulti_teleport 31] wcs_getviewcoords: The command 'wcs_getviewcoords' could not be found
[wcs/tools/ultimates/default/wcs_ulti_teleport 33] wcs_getdistance: The command 'wcs_getdistance' could not be found
[wcs/tools/ultimates/default/wcs_ulti_teleport 38] wcs_pushto: The command 'wcs_pushto' could not be found
[wcs/races/human_alliance/teleport 50] wcs_getviewcoords: The command 'wcs_getviewcoords' could not be found
[wcs/races/human_alliance/teleport 52] wcs_getdistance: The command 'wcs_getdistance' could not be found
".5" is an invalid value for "frame_rate:clamping".

[wcs/races/human_alliance/spawn 3] wcs_set_cooldown: The command 'wcs_set_cooldown' could not be found
```

**Comment by BrutalCSEjziponken** [comment]
Ok I just figured  something out...

bind l "+ability 1" - > And teleport works with new races, even tho its a really small two step jump.
But all the other WC mods Ive ever used used the command bind l "ultimate" to use those. Also the OLD races use bind l "ultimate".. Is it a good idea to mix like that? :P

**Comment by BrutalCSEjziponken** [comment]
I edited my first post.

**Comment by BrutalCSEjziponken** [comment]
Also levitation seems to bug sometimes giving you -gravity.

**Comment by BrutalCSEjziponken** [comment]
Also Human invisibilty not working (using sv_disable_immunity_alpha 1)

**Comment by ThaPwned** [comment]
> 
> 
> **Hm okay so I tested human teleport again. If I aim towards a wall straight infront of me, i get the small 2 step jump. But if I aim higher up i get that big jump. Seems like it should allow me to jump further when i aim straight forward?**

It all depends on angles and what not. I made it this way to mimic WCS 0.77's version.


> **Big:**
> https://gyazo.com/4c3b1128f2b187628d662033ce6534a8
> 
> **Small:**
> https://gyazo.com/2ac679d60dbf405d89b106fa018ff796
> 
> **Not sure about the effects, cant these be used?:**
> 
> > Effects:
> > This plugin contains the essential est_effects. The problem with CS:GO is, that most of the sprites are missing. If you want to use this version to its fullest:
> > Download the materials.zip from here: https://www.file-upload.net/download-12895000/materials.zip.html
> > Extract the materials.zip to your csgo folder
> 
> They have flames, lightning, laser beams etc.

You're free to install them on your server. I'd rather not require the players to download additional materials if it can be avoided.


> Also levitation seems to bug sometimes giving you -gravity.
> 
> Edit: Possible a DM bug aswell, I can reproduce it without DM.

Is this with `Undead Scourge`'s `Levitation` skill? If that is the case, it only sets the value that's retrieved from the `config.json` file, so make sure it's set correctly there. If it's another race, try to debug it and see if it's something there. Unfortunately, I cannot support races that's not on the contents repository.


> Also Human invisibilty not working (using sv_disable_immunity_alpha 1)
> Works with the OLD human race tho, but again then teleport dont work. :D

It appears to be a bug in CSGO, so not much I can do on my end, sorry.


I'd also appreciate it if you created a new issue instead of bundling them together here, as it makes it tricky to keep track on them. Thanks in advance.
