### ISSUE TITLE
late precache errors in console.log

### ISSUE THREAD

**Issue by NosferatuJoe** [ThaPwned/WCS#51]
Jan 27 19:38:26:  Late precache of effects/yellowflare.vmt
Jan 27 19:38:26:  Late precache of effects/combinemuzzle2.vmt
Jan 27 19:38:26:  Late precache of effects/combinemuzzle1.vmt

I keep getting these "features" in console.log although that the materials are present on the server and are properly included in the downloads.ini file.

All 3 of the effects are used in wcs.py.

Either the SM downloader/precacher doesn't work properly, or it misses a setting in the wcs.py

Maybe import "from engines.precache import Model" can be useful for this.

**Comment by srpg** [comment]
Maybe more useful is

from engines.server import engine_server

engine_server.precache_model(vmt)

it would precache the vmt

**Comment by NosferatuJoe** [comment]
> Maybe more useful is
> 
> from engines.server import engine_server
> 
> engine_server.precache_model(vmt)
> 
> it would precache the vmt

Hehe I don't know much about coding and found the code snippet somewhere, but you're probably right. 
Does it also exist for vtf's or don't they need precaching?
