### ISSUE TITLE
[REQUEST] Add firefix & mp_autokick 0 in core for CSS

### ISSUE THREAD

**Issue by NosferatuJoe** [ThaPwned/WCS#53]
Since almost everyone who tried running WCS on CSS stumbled upon these same old issues, I think it'd be nice for them to add these fixes to the core. That way we can prevent a lot of people reporting the same issues over and over again.

So adding mp_autokick 0 & the firefix.

I added the firefix for your convenience :)
[firefix.zip](https://github.com/ThaPwned/WCS/files/5890718/firefix.zip)

**Comment by srpg** [comment]
In Source.Python fire works fine with this code:

from players.helpers import index_from_userid
from entities.entity import Entity

def burn(userid, duration):
	try:
		Entity(index_from_userid(userid)).call_input('IgniteLifetime', float(duration))
	except ValueError:
		pass

**Comment by Xiazee** [comment]
> 
> 
> In Source.Python fire works fine with this code:
> 
> ```python
> from players.helpers import index_from_userid
> from entities.entity import Entity
> 
> def burn(userid, duration):
>   try:
>     Entity(index_from_userid(userid)).call_input('IgniteLifetime', float(duration))
>   except ValueError:
>     pass
> ```

I think issue is mainly with `es_fire`/`ent_fire`, which are being used by the ESS races. I think the `call_input()` method might completely skip the `ent_fire` command and just pass the input directly to the entity. This could perhaps be used to fix `es_fire`, although we might run into issues with `!activator` perhaps not being set then.

Alternatively we could just do as firefix does disable autokick for each player with `mp_disable_autokick <userid>`.

**Comment by srpg** [comment]
probaly in ESS races, has the issue, but i am not familar to to ESS code at all.

**Comment by NosferatuJoe** [comment]
This fix has been included in Manifest's WCS Essentials repo, which can be found here: https://github.com/ManifestManah/Warcraft-Source-Essentials
