### ISSUE TITLE
Effects

### ISSUE THREAD

**Issue by BrutalCSEjziponken** [ThaPwned/WCS#6]
https://www.file-upload.net/download-12895000/materials.zip.html

I dont know how to add new effects (Im not a coder). I did try for 2 hours but I couldn't make any of them work. I dont think people would mind if u had to download a few files. You always had to download in the old mods from 1.6. And a handful of files wold only take a few seconds to download the fist time.

Also if we add a custom one, would it actually be downloaded and preached (or whatever its called)? 

Either way, effects are important, cant really have a WCS server without that.

Maybe some of these could be used that comes with CSGO:

materials\effects\blueblacklargebeam.vtf
materials\effects\tesla_glow.vtf
materials\effects\fire_cloud1.vtf
materials\effects\energysplash.vtf
materials\effects\spark.vtf

materials\sprites\blueglow1.vtf
materials\sprites\blueflare1.vtf
materials\sprites\laserbeam.vtf
materials\sprites\rico1.vtf
materials\sprites\purplelaser1.vtf
materials\sprites\purpleglow1.vtf
materials\sprites\physbeam.vtf

**Comment by ThaPwned** [comment]
To change the effect model, you only have to change the path in the config.json file.
