### ISSUE TITLE
Problems with mysql

### ISSUE THREAD

**Issue by Lordi1985** [ThaPwned/WCS#72]
Hello, I wanted to set up a server with the Wcs mod today, which also worked very well. But I must have struggled with Mysql for an hour and then realized that it was probably not finished yet. Can you say how long it will be worked on. I know this is not an error, but it gives the impression that the mod works with mysql.

Kind regards

**Comment by NosferatuJoe** [comment]
Could you specify what's not working? I thought it worked with MySQL but just wasn't fully tested yet

**Comment by ThaPwned** [comment]
The MySQL part of the mod should be working. However, as @NosferatuJoe said, it haven't been tested that much, so there may be some weird quirks with it.
