### ISSUE TITLE
WCS setmodel not working properly

### ISSUE THREAD

**Issue by NosferatuJoe** [ThaPwned/WCS#77]
The "wcs setmodel" function needs a rework or atleast get looked at. I've tested the function on a prop and it doesn't make the original model invisible, thus showing you both models at the same time. I've also heard that this function was created for props so I do suggest renaming the function to wcs setmodelprop to make that more clear.

Although that it would be nice to have 1 function which works for both since models are an important feature of WCS and it's nice to have a solid function for it.

**Comment by NosferatuJoe** [comment]
Visual example of this nice feature:

![Uploading wcs setmodel.png…]()

**Comment by NosferatuJoe** [comment]
Visual example of this funny feature:
![wcs setmodel](https://user-images.githubusercontent.com/69318638/132054491-19d366e7-77b2-4811-bbb5-5919c3214416.png)

**Comment by ThaPwned** [comment]
As this command is not part of the core, I'm going to have to close it.
