### ISSUE TITLE
[REQUEST] exclude bots from wcstop ranking

### ISSUE THREAD

**Issue by NosferatuJoe** [ThaPwned/WCS#84]
I would be nice to be able to exclude bots from "wcstop", or atleast have (BOT) behind their names. But I would prefer having an option to exclude them because to be fair, they shouldn't even be in the list.

I've had this request multiple times from players playing on my server, players like to compete but not against the bots that play 24/7 on the server hehe.

**Comment by ThaPwned** [comment]
Bots are prefixed with `[BOT]` (configurable through `wcs_top_bot_prefix` in `config.cfg`) in wcstop since 022880b7ec91d727cf54d28ea8d126ec31cd5f46.
