### ISSUE TITLE
[QUESTION] Any way to use damage type DMG_FALL for damage commands? (Armor damage reduction)

### ISSUE THREAD

**Issue by missedbeat** [ThaPwned/WCS#85]
Example: wcs_dealdamage userid damage attacker  | wcs_dealdamage userid 50 attacker
In the case when the player has armor, he is inflicted incomplete damage, not 50 as planned. Also, the damage reduction in this case depends on which weapon the attacker is holding in his hands.
In the original ES mod, the damage system works through WCS_FALL, judging by the code. Is it possible to do the same here? 
Game: CSS OB, Linux host.
(My English is poor, I apologize for that. )

**Comment by ThaPwned** [comment]
`wcs_dealdamage` (and any damage-dealing method/command unless otherwise specified) will now use `ENERGYBEAM` as that ignores armor as well since `2d47dd2cf58a866467f0f8dd02faabc5261713eb`.
