### ISSUE TITLE
Ultimates and abilities

### ISSUE THREAD

**Issue by thehackedone** [ThaPwned/WCS#86]
It used to be +ability and +ultimate, but I can't seem to figure out how to use them now... whats the new command?

**Comment by NosferatuJoe** [comment]
It's ability and ultimate but without the "+", should work since I've always used it like this

**Comment by ThaPwned** [comment]
You can see what command a skill require by using `raceinfo` and navigating to your race. It'll show right after the skill name in parentheses.
