### ISSUE TITLE
You do not die on changerace if you recently used kill or changed race

### ISSUE THREAD

**Issue by Xiazee** [ThaPwned/WCS#89]
There is a cooldown of 5-10 seconds before the kill console command can be used again. So if you recently suicided or changed race, for example at the end of the previous round, you would be able to change race after spawning the following round, gaining the passives of the first and active abilities of the second.

We could either do something similar to `ent_fire userid sethealth 0` which damages the player when the number is lower than their current hp, but might be blocked by godmode and other skills.

Otherwise we might look into if it is possible to directly cause the player to die, without relying on any damage or console commands.

**Comment by ThaPwned** [comment]
This issue should be fixed with the latest version. Could you verify it?

**Comment by Xiazee** [comment]
The only places I could find where that doesn't work is with `god`(the real thing, not player.godmode), `buddha` or `noclip`.

**Comment by ThaPwned** [comment]
Those should be fixed with 892620e8a0478e5a485e086029200e1ca4e699e8.

**Comment by Xiazee** [comment]
That seems to do the trick.
