### ISSUE TITLE
Weird option numbering for skills in old style raceinfo menu

### ISSUE THREAD

**Issue by Xiazee** [ThaPwned/WCS#90]
![image](https://user-images.githubusercontent.com/9294009/154770278-f67da500-82b9-46cf-b7f8-2d7307a3358b.png)

It also counts the lines containing only text. Looks like Paged(ESC/Radio)Menu from Source.Python just enumerates the lines added to it.

**Comment by ThaPwned** [comment]
It was the simplest way of adding it without having to mess around with the ways the menus are handled. If you do have a solution to ignore the text in between the options, I wouldn't hesitate to accept it, hehe.
